### ISSUE TITLE
Gradle Build having issues with Zip64 shadow jar extension

### ISSUE THREAD

**Issue by abhayc-glitch** [abhayc-glitch/lumin#2]
I created a new Gradle vertx project using the official starter. Everything seemed to be going well but when i try to build my project i get this.
![Screen Shot 2021-08-17 at 10 21 54 AM](https://user-images.githubusercontent.com/78511893/129772133-32f25e1f-cfd3-441d-9fcc-b2c2b081ccd5.png)
Zip64 needed but how do i add that to my build.gradle file?
My build file is a .kts file

**Comment by theArnavPatil** [comment]
If your project is big and have lot's file files, maybe more than 65K files then you might end up getting error like that if you don't use Zip64.
You want to add
> isZip64 = true

to your build.gradle.kts
Then It will properly zip the files accordingly.

**Comment by abhayc-glitch** [comment]
@theArnavPatil 
Thanks! Worked for me
