### ISSUE TITLE
Vertx Router throws an error for router acceptance

### ISSUE THREAD

**Issue by abhayc-glitch** [abhayc-glitch/lumin#3]
When i create a new Http server in application, I am trying to make the Base Router accept the connection but it gives an error.
![Screen Shot 2021-08-17 at 3 45 34 PM](https://user-images.githubusercontent.com/78511893/129810439-445b0dc5-e122-494e-b89e-33132e93bfba.png)
I checked all my imports and there methods. There is no proper acceptance method in the docs for this. How can i do it?

**Comment by theArnavPatil** [comment]
The baseRouter doesn't need an `::accept` or `.accept`. Vertx 4 automatically does that for you. You seem to be writing a traditional way of routing. You just need to call it in the `createHTTPserver` method that's all!

**Comment by abhayc-glitch** [comment]
Thank You!
